# Generated by Django 3.0.3 on 2020-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_point',
            name='text',
            field=models.TextField(default='woops'),
            preserve_default=False,
        ),
    ]
