# Generated by Django 3.0.3 on 2020-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_bio_point_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
