# Generated by Django 3.0.3 on 2020-06-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_about_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('post_amount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='project_post',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='project_post',
            name='link',
        ),
        migrations.AlterField(
            model_name='project_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_post_images'),
        ),
        migrations.AddField(
            model_name='project_post',
            name='subgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Project_Subgroup'),
            preserve_default=False,
        ),
    ]
