# Generated by Django 3.0.3 on 2020-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_remove_project_post_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_subgroup',
            name='title_visible',
            field=models.BooleanField(default=False),
        ),
    ]
