# Generated by Django 3.0.3 on 2020-06-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_project_subgroup_title_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_post',
            name='subgroup',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
