# Generated by Django 3.0.3 on 2020-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_project_post_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_post',
            name='skills',
            field=models.TextField(default='skills'),
            preserve_default=False,
        ),
    ]
