# Generated by Django 3.0.3 on 2020-06-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_project_post_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_subgroup',
            name='post_amount',
            field=models.CharField(max_length=200),
        ),
    ]
