# Generated by Django 3.0.3 on 2020-06-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20200626_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_post',
            name='link',
            field=models.TextField(default='link'),
            preserve_default=False,
        ),
    ]
