# Generated by Django 3.0.3 on 2020-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_project_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_post',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
